services:
  postgres:
    image: postgres
    container_name: postgres-db
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql #This is the path to a database schema seed.

volumes:
  postgres-db: